name: Create PR
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  git_name:
    description: 
    required: true
  git_email:
    description: 
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        set +e

        if git diff --exit-code --quiet; then
          echo "ERROR: Oops! You need to make some changes before creating a pull request."
          exit 1
        fi

        exit 69

        git config user.name "${{ inputs.git_name }}"
        git config user.email "${{ inputs.git_email }}"

        branch="action-create-PR-$(date +'%Y%m%d_%H%M%S')"
        git checkout -b $branch -q

        git add .
        git commit -m "foo bar baz" -q

        git push origin $branch

        ## TODO: Find a way so users don't have to check the box in order to use this action
        gh pr create -f
        if [ $? -eq 1 ]; then
          echo "ERROR: Oops! You need to allow GitHub Actions to create a PR by checking the checkbox 'Allow GitHub Actions to create and approve pull requests' at https://github.com/$GITHUB_REPOSITORY/settings/actions ."
          exit 1
        fi
      shell: bash